# FTPでアップロードする。

name: Deploy via FTPS

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:
    inputs:
      target:
        description: "Deployment target"
        required: true
        type: choice
        options:
          - production
          - development
        default: development
      source_ref:
        description: "Branch or tag to build"
        required: true
        default: master

permissions: {}

jobs:
  deploy-production:
    if: (github.event_name == 'push' && github.ref_name == 'master') || (github.event_name == 'workflow_dispatch' && inputs.target == 'production')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.inputs.source_ref || github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          SITE_ENV: production
          SITE_URL: https://tkspecial.bunkasai.info
          SITE_BASE: /
        run: npm run build

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload to FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTPS_HOST_TKSPECIAL }}
          username: ${{ secrets.FTPS_USER_TKSPECIAL }}
          password: ${{ secrets.FTPS_PASS_TKSPECIAL }}
          local-dir: dist/
          server-dir: ${{ secrets.FTPS_PATH_TKSPECIAL }}

  deploy-development:
    if: (github.event_name == 'push' && github.ref_name == 'dev') || (github.event_name == 'workflow_dispatch' && inputs.target == 'development')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.inputs.source_ref || github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          SITE_ENV: development
          SITE_URL: https://specialtest.bunkasai.info
          SITE_BASE: /
        run: npm run build

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload to FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTPS_HOST_SPECIALTEST }}
          username: ${{ secrets.FTPS_USER_SPECIALTEST }}
          password: ${{ secrets.FTPS_PASS_SPECIALTEST }}
          local-dir: dist/
          server-dir: ${{ secrets.FTPS_PATH_SPECIALTEST }}
